[phases.setup]
nixPkgs = ["python39", "python39Packages.pip", "glibcLocales"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "export LC_ALL=en_US.UTF-8 && python simple_api.py"